# Generated by Django 4.1.3 on 2022-11-19 02:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=5)),
                ('capacidade', models.IntegerField()),
            ],
        ),
    ]
