# Generated by Django 4.1.3 on 2022-11-19 03:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('empresa_produtora', models.CharField(max_length=255)),
                ('nacional', models.BooleanField()),
                ('censura', models.CharField(max_length=255)),
                ('duracao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.ator')),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.filme')),
            ],
        ),
    ]
