# Generated by Django 4.1.3 on 2022-12-01 00:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_ator_filme_atuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_final', models.DateField()),
                ('horario_inicio', models.TimeField()),
                ('horario_final', models.TimeField()),
                ('filme_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.filme')),
                ('sala_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.sala')),
            ],
        ),
    ]
