# Generated by Django 4.1.3 on 2022-12-01 01:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_cronograma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cpf', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('cpf_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItemLanchonete',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingresso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('categoria', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('id_cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.cronograma')),
            ],
        ),
        migrations.CreateModel(
            name='CompraProdutos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.compra')),
                ('id_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.itemlanchonete')),
            ],
        ),
        migrations.CreateModel(
            name='CompraIngressos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.compra')),
                ('id_ingresso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinema.ingresso')),
            ],
        ),
    ]
