# Generated by Django 4.1.3 on 2022-12-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_cliente_compra_itemlanchonete_ingresso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
